Repository frequency-chain/frequency, pull requests merged in 2023-05, with the labels that each got.

#1453 Decrease use of parameter types
  Cargo.lock
  common/primitives/src/msa.rs
  pallets/capacity/src/tests/epochs_tests.rs
  pallets/capacity/src/tests/mock.rs
  pallets/capacity/src/tests/testing_utils.rs
  pallets/frequency-tx-payment/src/tests/mock.rs
  pallets/handles/src/tests/mock.rs
  pallets/messages/src/tests/mock.rs
  pallets/messages/src/tests/other_tests.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/tests/delegation_tests.rs
  pallets/msa/src/tests/mock.rs
  pallets/msa/src/tests/other_tests.rs
  pallets/msa/src/tests/replay_tests.rs
  pallets/msa/src/tests/schema_permission_tests.rs
  pallets/msa/src/tests/signature_registry_tests.rs
  pallets/schemas/src/tests/mock.rs
  pallets/stateful-storage/src/lib.rs
  pallets/stateful-storage/src/tests/apply_item_actions_tests.rs
  pallets/stateful-storage/src/tests/delete_page_tests.rs
  pallets/stateful-storage/src/tests/mock.rs
  pallets/stateful-storage/src/tests/upsert_page_tests.rs
  pallets/time-release/Cargo.toml
  pallets/time-release/src/mock.rs
  pallets/time-release/src/tests.rs
  runtime/common/src/constants.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1452 Restrict Pays:No call in batches
  integration-tests/miscellaneous/utilityBatch.test.ts
  integration-tests/scaffolding/extrinsicHelpers.ts
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1477 Build new binary and use it for integration tests
  .github/workflows/verify-pr-commit.yml
Labels: metadata-mismatch

#1464 1401 Build/run Frequency runtime without a relay chain
  .github/workflows/verify-pr-commit.yml
  Makefile
  README.md
  integration-tests/package-lock.json
  node/Cargo.toml
  node/cli/Cargo.toml
  node/cli/build.rs
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/cli/src/lib.rs
  node/cli/src/run_as_localchain.rs
  node/cli/src/run_as_parachain.rs
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/chain_spec/frequency_rococo.rs
  node/service/src/lib.rs
  node/service/src/service.rs
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/common/src/lib.rs
  runtime/frequency/Cargo.toml
  runtime/frequency/src/lib.rs
  scripts/init.sh
Labels: metadata-mismatch

#1372 chore(capacity): address PR 827 comments
  pallets/capacity/src/lib.rs
  pallets/capacity/src/weights.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1511 refactor: feature frequency-local => frequency-rococo-local
  .env.sample
  .github/workflows/merge-pr.yml
  .github/workflows/release.yml
  .github/workflows/verify-pr-commit.yml
  Makefile
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/chain_spec/frequency_rococo.rs
  scripts/generate_js_definitions.sh
  scripts/generate_specs.sh
  scripts/init.sh
Labels: change/major

#1497 test(e2e-tests): Capacity staking from multiple msa to one provider; …
  integration-tests/capacity/replenishment.test.ts
  integration-tests/capacity/staking.test.ts
  integration-tests/capacity/transactions.test.ts
  integration-tests/messages/addIPFSMessage.test.ts
  integration-tests/scaffolding/extrinsicHelpers.ts
  integration-tests/scaffolding/helpers.ts
  scripts/run_integration_tests.sh
Labels: chore, Capacity, test
