Repository frequency-chain/frequency, pull requests merged in 2023-01, with the labels that each got.

#880 chore(design-docs): update design docs
  designdocs/capacity.md
Labels: Capacity

#751 [CHORE] Upgrade version to v0.9.32
  .github/workflows/verify-pr-commit.yml
  Cargo.lock
  common/helpers/Cargo.toml
  common/primitives/Cargo.toml
  docker/docker-compose.yml
  node/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  node/service/src/service.rs
  pallets/messages/Cargo.toml
  pallets/messages/src/rpc/Cargo.toml
  pallets/messages/src/runtime-api/Cargo.toml
  pallets/messages/src/weights.rs
  pallets/msa/Cargo.toml
  pallets/msa/src/lib.rs
  pallets/msa/src/rpc/Cargo.toml
  pallets/msa/src/rpc/src/lib.rs
  pallets/msa/src/runtime-api/Cargo.toml
  pallets/msa/src/weights.rs
  pallets/schemas/Cargo.toml
  pallets/schemas/src/rpc/Cargo.toml
  pallets/schemas/src/runtime-api/Cargo.toml
  pallets/schemas/src/weights.rs
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/common/src/weights/orml_vesting.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_session.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/frequency/Cargo.toml
  runtime/frequency/src/lib.rs
  rust-toolchain.toml
  scripts/generate_relay_specs.sh
Labels: metadata-mismatch, change/major

#905 feat(ipfs): add CID validation to add_ipfs_message #786
  Cargo.lock
  common/primitives/src/messages.rs
  integration-tests/.mocharc.js
  integration-tests/messages/addIPFSMessage.test.ts
  integration-tests/messages/loadIPFS.js
  integration-tests/package-lock.json
  integration-tests/package.json
  pallets/messages/Cargo.toml
  pallets/messages/src/benchmarking.rs
  pallets/messages/src/lib.rs
  pallets/messages/src/mock.rs
  pallets/messages/src/rpc/src/tests/mod.rs
  pallets/messages/src/tests.rs
  pallets/messages/src/weights.rs
  runtime/frequency/src/lib.rs
  scripts/run_integration_tests.sh
Labels: metadata-mismatch, change/major

#954 Polkadot 0.9.33 UPGRADE
  Cargo.lock
  common/helpers/Cargo.toml
  common/primitives/Cargo.toml
  docker/docker-compose.yml
  node/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/service.rs
  pallets/messages/Cargo.toml
  pallets/messages/src/rpc/Cargo.toml
  pallets/messages/src/runtime-api/Cargo.toml
  pallets/msa/Cargo.toml
  pallets/msa/src/rpc/Cargo.toml
  pallets/msa/src/runtime-api/Cargo.toml
  pallets/schemas/Cargo.toml
  pallets/schemas/src/rpc/Cargo.toml
  pallets/schemas/src/runtime-api/Cargo.toml
  runtime/common/Cargo.toml
  runtime/frequency/Cargo.toml
  runtime/frequency/src/lib.rs
  scripts/generate_relay_specs.sh
Labels: metadata-mismatch

#943 Spike/offchain indexing: using offchain_index and offchain_worker to persist reverse map(?)
  Cargo.lock
  common/primitives/Cargo.toml
  common/primitives/src/lib.rs
  common/primitives/src/offchain.rs
  js/api-augment/definitions/msa.ts
  js/api-augment/package-lock.json
  pallets/msa/Cargo.toml
  pallets/msa/src/lib.rs
  pallets/msa/src/mock.rs
  pallets/msa/src/offchain_storage.rs
  pallets/msa/src/rpc/src/lib.rs
  pallets/msa/src/runtime-api/src/lib.rs
  pallets/msa/src/tests.rs
  runtime/frequency/src/lib.rs
  scripts/init.sh
Labels: metadata-mismatch

#970 Polkadot 0.9.36 upgrade
  Cargo.lock
  common/helpers/Cargo.toml
  common/primitives/Cargo.toml
  docker/docker-compose.yml
  node/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  node/service/src/service.rs
  pallets/messages/Cargo.toml
  pallets/messages/src/lib.rs
  pallets/messages/src/rpc/Cargo.toml
  pallets/messages/src/rpc/src/lib.rs
  pallets/messages/src/runtime-api/Cargo.toml
  pallets/messages/src/weights.rs
  pallets/msa/Cargo.toml
  pallets/msa/src/lib.rs
  pallets/msa/src/rpc/Cargo.toml
  pallets/msa/src/runtime-api/Cargo.toml
  pallets/msa/src/weights.rs
  pallets/schemas/Cargo.toml
  pallets/schemas/src/lib.rs
  pallets/schemas/src/rpc/Cargo.toml
  pallets/schemas/src/runtime-api/Cargo.toml
  pallets/schemas/src/weights.rs
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/common/src/weights/block_weights.rs
  runtime/common/src/weights/extrinsic_weights.rs
  runtime/common/src/weights/orml_vesting.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_session.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/frequency/Cargo.toml
  runtime/frequency/src/lib.rs
  scripts/generate_relay_specs.sh
Labels: metadata-mismatch

#983 feat(event-tuple-to-struct): Use structs instead of tuples for extrinsic events
  integration-tests/messages/addIPFSMessage.test.ts
  js/api-augment/package-lock.json
  js/api-augment/package.json
  pallets/schemas/src/lib.rs
  pallets/schemas/src/tests.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#986 chore(capacity): organize unit tests into separate files
  pallets/capacity/src/extrinsics_tests.rs
  pallets/capacity/src/helpers_tests.rs
  pallets/capacity/src/lib.rs
  pallets/capacity/src/tests.rs
  pallets/capacity/src/types_tests.rs
Labels: metadata-mismatch, Capacity

#978 chore(capacity): Update the stake event to also include issued capacity
  designdocs/capacity.md
  pallets/capacity/src/benchmarking.rs
  pallets/capacity/src/extrinsics_tests.rs
  pallets/capacity/src/lib.rs
Labels: metadata-mismatch, Capacity

#959 [Capacity] unstake benchmarking
  pallets/capacity/src/benchmarking.rs
  pallets/capacity/src/extrinsics_tests.rs
  pallets/capacity/src/lib.rs
  pallets/capacity/src/weights.rs
Labels: metadata-mismatch
