Repository frequency-chain/frequency, pull requests merged in 2023-04, with the labels that each got.

#1310 Address more PR comments
  pallets/capacity/src/lib.rs
Labels: metadata-mismatch, Capacity

#1302 Update design docs and address PR comments for #827: remove CurrentEpochUsedCapacity
  designdocs/capacity.md
  pallets/capacity/src/benchmarking.rs
  pallets/capacity/src/lib.rs
  pallets/capacity/src/tests/other_tests.rs
Labels: metadata-mismatch

#1324 fix(FrqcyTxPayment): ensure pay_with_capacity errors
  Makefile
  integration-tests/capacity/transactions.test.ts
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/tests.rs
  pallets/frequency-tx-payment/src/weights.rs
Labels: metadata-mismatch, Capacity

#1321 Update pays with capacity integration test to check for correctly reduced capacity
  integration-tests/capacity/transactions.test.ts
Labels: metadata-mismatch, Capacity

#1330 feat(FrqTxPayment): add extension weights
  pallets/capacity/src/lib.rs
  pallets/frequency-tx-payment/src/lib.rs
Labels: metadata-mismatch

#1331 Refactor Capacity Integration Tests
  integration-tests/capacity/replenishment.test.ts
  integration-tests/capacity/transactions.test.ts
  integration-tests/scaffolding/helpers.ts
Labels: metadata-mismatch

#827 feat(capacity): add staking and paying with Capacity
  Cargo.lock
  Makefile
  common/primitives/src/benchmarks.rs
  common/primitives/src/capacity.rs
  common/primitives/src/lib.rs
  designdocs/capacity.md
  integration-tests/capacity/replenishment.test.ts
  integration-tests/capacity/staking.test.ts
  integration-tests/capacity/transactions.test.ts
  integration-tests/package-lock.json
  integration-tests/scaffolding/extrinsicHelpers.ts
  integration-tests/scaffolding/helpers.ts
  node/cli/Cargo.toml
  node/cli/src/benchmarking.rs
  pallets/capacity/Cargo.toml
  pallets/capacity/src/benchmarking.rs
  pallets/capacity/src/lib.rs
  pallets/capacity/src/tests/capacity_details_tests.rs
  pallets/capacity/src/tests/epochs_tests.rs
  pallets/capacity/src/tests/mock.rs
  pallets/capacity/src/tests/mod.rs
  pallets/capacity/src/tests/other_tests.rs
  pallets/capacity/src/tests/replenishment_tests.rs
  pallets/capacity/src/tests/stake_and_deposit_tests.rs
  pallets/capacity/src/tests/staking_account_details_tests.rs
  pallets/capacity/src/tests/staking_target_details_tests.rs
  pallets/capacity/src/tests/testing_utils.rs
  pallets/capacity/src/tests/unstaking_tests.rs
  pallets/capacity/src/tests/withdraw_unstaked_tests.rs
  pallets/capacity/src/tests/withdrawal_tests.rs
  pallets/capacity/src/types.rs
  pallets/capacity/src/weights.rs
  pallets/frequency-tx-payment/Cargo.toml
  pallets/frequency-tx-payment/src/benchmarking.rs
  pallets/frequency-tx-payment/src/capacity_stable_weights.rs
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/mock.rs
  pallets/frequency-tx-payment/src/payment.rs
  pallets/frequency-tx-payment/src/tests.rs
  pallets/frequency-tx-payment/src/types.rs
  pallets/frequency-tx-payment/src/weights.rs
  pallets/msa/src/lib.rs
  pallets/stateful-storage/src/lib.rs
  runtime/common/src/constants.rs
  runtime/common/src/weights/block_weights.rs
  runtime/common/src/weights/extrinsic_weights.rs
  runtime/frequency/Cargo.toml
  runtime/frequency/src/lib.rs
  scripts/run_benchmarks.sh
Labels: project, metadata-mismatch

#1345 Use `String` for ease of use of api library
  integration-tests/handles/handles.test.ts
  integration-tests/package-lock.json
  js/api-augment/definitions/handles.ts
Labels: metadata-mismatch

#1346 Batched Capacity Transactions
  Cargo.lock
  common/primitives/src/node.rs
  pallets/frequency-tx-payment/Cargo.toml
  pallets/frequency-tx-payment/src/benchmarking.rs
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/mock.rs
  pallets/frequency-tx-payment/src/tests.rs
  pallets/frequency-tx-payment/src/weights.rs
  runtime/common/src/constants.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1354 [Handles] signature mortality
  common/primitives/src/handles.rs
  integration-tests/handles/handles.test.ts
  integration-tests/package-lock.json
  integration-tests/scaffolding/extrinsicHelpers.ts
  pallets/handles/src/benchmarking.rs
  pallets/handles/src/handles-utils/src/converter.rs
  pallets/handles/src/handles-utils/src/lib.rs
  pallets/handles/src/handles-utils/src/validator.rs
  pallets/handles/src/handles_signed_extension.rs
  pallets/handles/src/lib.rs
  pallets/handles/src/tests/handle_creation_tests.rs
  pallets/handles/src/tests/handle_retirements_tests.rs
  pallets/handles/src/tests/handles_replay_attack_test.rs
  pallets/handles/src/tests/mock.rs
  pallets/handles/src/tests/mod.rs
  pallets/handles/src/tests/signed_extension_tests.rs
  pallets/handles/src/weights.rs
  runtime/frequency/src/lib.rs
Labels: blocked, metadata-mismatch

#1395 Capacity Batching Integration Tests
  integration-tests/capacity/transactions.test.ts
  integration-tests/package-lock.json
  integration-tests/scaffolding/extrinsicHelpers.ts
Labels: metadata-mismatch

#1312 [Handles] Handles on Frequency
  Cargo.lock
  Makefile
  common/primitives/src/handles.rs
  common/primitives/src/lib.rs
  designdocs/user-handles.md
  integration-tests/.load-test.mocharc.json
  integration-tests/capacity/transactions.test.ts
  integration-tests/handles/handles.test.ts
  integration-tests/package-lock.json
  integration-tests/scaffolding/extrinsicHelpers.ts
  integration-tests/scaffolding/helpers.ts
  js/api-augment/definitions/handles.ts
  js/api-augment/definitions/index.ts
  js/api-augment/test/index.test.ts
  node/cli/Cargo.toml
  node/cli/src/benchmarking.rs
  node/service/Cargo.toml
  node/service/src/rpc/mod.rs
  pallets/capacity/src/tests/mock.rs
  pallets/frequency-tx-payment/src/capacity_stable_weights.rs
  pallets/frequency-tx-payment/src/mock.rs
  pallets/handles/Cargo.toml
  pallets/handles/src/benchmarking.rs
  pallets/handles/src/handles-utils/Cargo.toml
  pallets/handles/src/handles-utils/src/confusables.rs
  pallets/handles/src/handles-utils/src/confuseables-main.rs
  pallets/handles/src/handles-utils/src/converter.rs
  pallets/handles/src/handles-utils/src/data/confusable_characters.txt
  pallets/handles/src/handles-utils/src/lib.rs
  pallets/handles/src/handles-utils/src/suffix.rs
  pallets/handles/src/handles-utils/src/tests/converter_tests.rs
  pallets/handles/src/handles-utils/src/tests/mod.rs
  pallets/handles/src/handles-utils/src/tests/validator_tests.rs
  pallets/handles/src/handles-utils/src/types.rs
  pallets/handles/src/handles-utils/src/validator.rs
  pallets/handles/src/handles_signed_extension.rs
  pallets/handles/src/lib.rs
  pallets/handles/src/rpc/Cargo.toml
  pallets/handles/src/rpc/src/lib.rs
  pallets/handles/src/rpc/src/tests/mod.rs
  pallets/handles/src/rpc/src/tests/rpc_mock.rs
  pallets/handles/src/runtime-api/Cargo.toml
  pallets/handles/src/runtime-api/src/lib.rs
  pallets/handles/src/tests/handle_creation_tests.rs
  pallets/handles/src/tests/handle_retirements_tests.rs
  pallets/handles/src/tests/handles_replay_attack_test.rs
  pallets/handles/src/tests/mock.rs
  pallets/handles/src/tests/mod.rs
  pallets/handles/src/tests/signed_extension_tests.rs
  pallets/handles/src/weights.rs
  pallets/msa/Cargo.toml
  pallets/msa/src/lib.rs
  pallets/msa/src/tests/mock.rs
  pallets/msa/src/tests/retirement_tests.rs
  runtime/common/src/constants.rs
  runtime/frequency/Cargo.toml
  runtime/frequency/src/lib.rs
  scripts/run_benchmarks.sh
Labels: metadata-mismatch

#1410 set token:capacity ratio to 50, set thaw period to 30 days.
  integration-tests/capacity/replenishment.test.ts
  integration-tests/capacity/staking.test.ts
  integration-tests/capacity/transactions.test.ts
  integration-tests/package-lock.json
  integration-tests/scaffolding/helpers.ts
  pallets/capacity/src/benchmarking.rs
  pallets/capacity/src/lib.rs
  pallets/capacity/src/tests/capacity_details_tests.rs
  pallets/capacity/src/tests/mock.rs
  pallets/capacity/src/tests/other_tests.rs
  pallets/capacity/src/tests/stake_and_deposit_tests.rs
  pallets/capacity/src/tests/staking_account_details_tests.rs
  pallets/capacity/src/tests/unstaking_tests.rs
  pallets/capacity/src/types.rs
  pallets/frequency-tx-payment/src/mock.rs
  pallets/frequency-tx-payment/src/tests.rs
  runtime/common/src/constants.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1428 Type alias handles
  common/primitives/src/handles.rs
  pallets/handles/src/lib.rs
  pallets/handles/src/rpc/src/lib.rs
  pallets/handles/src/rpc/src/tests/mod.rs
  pallets/handles/src/runtime-api/src/lib.rs
  pallets/handles/src/tests/handle_creation_tests.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1441 fix(Capacity) Ensure Epoch incrementing when not starting chain from block 0
  pallets/capacity/src/lib.rs
  pallets/capacity/src/tests/epochs_tests.rs
  pallets/capacity/src/tests/testing_utils.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1443 fix type definition mismatch for schemas
  integration-tests/scaffolding/extrinsicHelpers.ts
  integration-tests/schemas/createSchema.test.ts
  js/api-augment/definitions/schemas.ts
Labels: bug
