Repository frequency-chain/frequency, pull requests merged in 2023-03, with the labels that each got.

#1150 Feat/capacity add benchmarking
  Makefile
  pallets/capacity/src/benchmarking.rs
  pallets/frequency-tx-payment/src/benchmarking.rs
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/mock.rs
  pallets/frequency-tx-payment/src/tests.rs
  pallets/frequency-tx-payment/src/weights.rs
  runtime/frequency/src/lib.rs
  scripts/run_all_benchmarks.sh
Labels: metadata-mismatch

#1158 Feat/whitelist capacity eligible calls #1013
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/mock.rs
  pallets/frequency-tx-payment/src/tests.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1161 Emit an event when capacity is withdrawn
  designdocs/capacity.md
  pallets/capacity/src/helpers_tests.rs
  pallets/capacity/src/lib.rs
Labels: metadata-mismatch

#1165 Chore/capacity custom error messages
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/tests.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1170 Removed grant_schema_permissions()
  integration-tests/scenarios/grantDelegation.test.ts
  pallets/msa/src/benchmarking.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/tests.rs
  pallets/msa/src/weights.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch, change/major

#1166 Chore/renames and fix bug
  common/primitives/src/capacity.rs
  designdocs/capacity.md
  pallets/capacity/src/benchmarking.rs
  pallets/capacity/src/extrinsics_tests.rs
  pallets/capacity/src/helpers_tests.rs
  pallets/capacity/src/lib.rs
  pallets/capacity/src/testing_utils.rs
  pallets/capacity/src/types.rs
  pallets/capacity/src/types_tests.rs
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/mock.rs
Labels: metadata-mismatch

#1169 Removed call filters for Mainnet
  runtime/frequency/src/lib.rs
Labels: change/major

#1179 chore(staking): final integration tests for staking
  integration-tests/capacity/staking.test.ts
  integration-tests/package-lock.json
Labels: metadata-mismatch

#1184 Optimize registry and fix weights
  common/primitives/src/msa.rs
  pallets/msa/src/audit_replay_tests.rs
  pallets/msa/src/benchmarking.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/migration.rs
  pallets/msa/src/signature_registry_tests.rs
  pallets/msa/src/tests.rs
  pallets/msa/src/weights.rs
  runtime/frequency/src/lib.rs
  scripts/run_benchmark.sh
Labels: metadata-mismatch

#1180 Lazily refill capacity if it's time, before withdrawing fees
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/tests.rs
Labels: metadata-mismatch

#1199 Bugs/bad withdraw behavior
  designdocs/capacity.md
  integration-tests/capacity/transactions.test.ts
  pallets/capacity/src/extrinsics_tests.rs
  pallets/capacity/src/mock.rs
  pallets/capacity/src/types.rs
  pallets/capacity/src/types_tests.rs
  pallets/frequency-tx-payment/src/mock.rs
Labels: metadata-mismatch

#1200 feat(capacity-tx): make fees stable
  pallets/frequency-tx-payment/src/capacity_stable_weights.rs
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/mock.rs
  pallets/frequency-tx-payment/src/tests.rs
  pallets/frequency-tx-payment/src/types.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1203 [Capacity] integration tests for transacting #889
  integration-tests/capacity/transactions.test.ts
  integration-tests/package-lock.json
  integration-tests/scaffolding/extrinsicHelpers.ts
  integration-tests/scaffolding/helpers.ts
Labels: metadata-mismatch

#1243 Bugfix/capacity integration test scripts
  integration-tests/capacity/transactions.test.ts
  scripts/run_integration_tests.sh
Labels: metadata-mismatch

#1246 feat(capacity): allow p.g tx's to pay with capacity
  pallets/frequency-tx-payment/src/capacity_stable_weights.rs
  pallets/stateful-storage/src/lib.rs
  pallets/stateful-storage/src/tests.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1248 Replenishment integration tests
  integration-tests/capacity/replenishment.test.ts
  integration-tests/capacity/transactions.test.ts
  integration-tests/scaffolding/extrinsicHelpers.ts
Labels: metadata-mismatch

#1256 Capacity staking min token balance
  designdocs/capacity.md
  integration-tests/capacity/replenishment.test.ts
  integration-tests/capacity/transactions.test.ts
  integration-tests/scaffolding/helpers.ts
  pallets/capacity/src/benchmarking.rs
  pallets/capacity/src/lib.rs
  pallets/capacity/src/tests/mock.rs
  pallets/capacity/src/tests/stake_and_deposit_tests.rs
  pallets/capacity/src/tests/staking_account_details_tests.rs
  pallets/capacity/src/types.rs
  pallets/capacity/src/weights.rs
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/mock.rs
  runtime/common/src/constants.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1272 staeful-storage: reduced paginated page size
  designdocs/graph_sdk.md
  runtime/common/src/constants.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1266 Time Release Pallet (Port vesting pallet)
  Cargo.lock
  Makefile
  integration-tests/package-lock.json
  integration-tests/scaffolding/extrinsicHelpers.ts
  integration-tests/time-release/timeRelease.ts
  node/service/src/chain_spec/frequency.rs
  node/service/src/chain_spec/frequency_rococo.rs
  pallets/time-release/Cargo.toml
  pallets/time-release/README.md
  pallets/time-release/src/benchmarking.rs
  pallets/time-release/src/lib.rs
  pallets/time-release/src/mock.rs
  pallets/time-release/src/tests.rs
  pallets/time-release/src/types.rs
  pallets/time-release/src/weights.rs
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/orml_vesting.rs
  runtime/frequency/Cargo.toml
  runtime/frequency/src/benchmarking/mod.rs
  runtime/frequency/src/benchmarking/vesting.rs
  runtime/frequency/src/lib.rs
  scripts/run_benchmarks.sh
Labels: metadata-mismatch

#1299 chore(capacity): organize integration test
  integration-tests/capacity/replenishment.test.ts
  integration-tests/capacity/staking.test.ts
  integration-tests/capacity/transactions.test.ts
  integration-tests/package-lock.json
  integration-tests/scaffolding/helpers.ts
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch
