Repository frequency-chain/frequency, pull requests merged in 2023-12, with the labels that each got.

#1763 Feat/separate unlock chunks #1753
  designdocs/capacity.md
  designdocs/capacity_staking_rewards_implementation.md
  pallets/capacity/src/benchmarking.rs
  pallets/capacity/src/lib.rs
  pallets/capacity/src/migration/mod.rs
  pallets/capacity/src/migration/v2.rs
  pallets/capacity/src/tests/migrate_v2_tests.rs
  pallets/capacity/src/tests/mod.rs
  pallets/capacity/src/tests/other_tests.rs
  pallets/capacity/src/tests/stake_and_deposit_tests.rs
  pallets/capacity/src/tests/staking_account_details_tests.rs
  pallets/capacity/src/tests/unlock_chunks_tests.rs
  pallets/capacity/src/tests/unstaking_tests.rs
  pallets/capacity/src/tests/withdraw_unstaked_tests.rs
  pallets/capacity/src/types.rs
  pallets/capacity/src/weights.rs
  runtime/frequency/src/lib.rs
Labels: documentation, metadata-changed, change/major, Storage Migration

#1784 adding schema names support
  common/primitives/src/schema.rs
  e2e/package-lock.json
  e2e/scaffolding/extrinsicHelpers.ts
  e2e/scaffolding/helpers.ts
  e2e/schemas/createSchema.test.ts
  e2e/sudo/sudo.test.ts
  js/api-augment/definitions/schemas.ts
  pallets/schemas/src/benchmarking.rs
  pallets/schemas/src/lib.rs
  pallets/schemas/src/migration/mod.rs
  pallets/schemas/src/migration/v3.rs
  pallets/schemas/src/rpc/src/lib.rs
  pallets/schemas/src/rpc/src/tests/mod.rs
  pallets/schemas/src/runtime-api/src/lib.rs
  pallets/schemas/src/tests/deprecated_tests.rs
  pallets/schemas/src/tests/migrations_tests.rs
  pallets/schemas/src/tests/mock.rs
  pallets/schemas/src/tests/mod.rs
  pallets/schemas/src/tests/other_tests.rs
  pallets/schemas/src/types.rs
  pallets/schemas/src/weights.rs
  runtime/frequency/src/lib.rs
Labels: metadata-changed

#1779 chore: Replace Currency->fungible migration for capacity pallet
  .cargo-deny.toml
  .github/workflows/common/codecov/action.yml
  .vscode/settings.json
  Cargo.lock
  e2e/package-lock.json
  pallets/capacity/Cargo.toml
  pallets/capacity/src/benchmarking.rs
  pallets/capacity/src/lib.rs
  pallets/capacity/src/migration/mod.rs
  pallets/capacity/src/migration/v2.rs
  pallets/capacity/src/migration/v3.rs
  pallets/capacity/src/tests/mock.rs
  pallets/capacity/src/tests/other_tests.rs
  pallets/capacity/src/tests/stake_and_deposit_tests.rs
  pallets/capacity/src/tests/unstaking_tests.rs
  pallets/capacity/src/tests/withdraw_unstaked_tests.rs
  pallets/capacity/src/weights.rs
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/payment.rs
  pallets/frequency-tx-payment/src/tests/mock.rs
  pallets/schemas/src/migration/v3.rs
  pallets/time-release/Cargo.toml
  runtime/common/src/constants.rs
  runtime/frequency/src/lib.rs
  scripts/upgrade_accounts.py
Labels: metadata-changed

#1808 fix: Update Docker image version and relay chain spec
  resources/rococo-local.json
  scripts/generate_relay_specs.sh
Labels: chore
