Repository frequency-chain/frequency, pull requests merged in 2023-02, with the labels that each got.

#1005 feat(capacity): add replenishable traits
  common/primitives/src/capacity.rs
  pallets/capacity/src/benchmarking.rs
  pallets/capacity/src/helpers_tests.rs
  pallets/capacity/src/lib.rs
  pallets/capacity/src/testing_utils.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1011 Paginated page types
  pallets/messages/src/tests.rs
  pallets/stateful-storage/src/stateful_child_tree.rs
  pallets/stateful-storage/src/tests.rs
  pallets/stateful-storage/src/types.rs
Labels: Private Graph

#1028 321 propose to be a provider
  Cargo.lock
  pallets/msa/Cargo.toml
  pallets/msa/src/audit_replay_tests.rs
  pallets/msa/src/benchmarking.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/mock.rs
  pallets/msa/src/signature_registry_tests.rs
  pallets/msa/src/tests.rs
  pallets/msa/src/weights.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1066 Chore/remove sudo storage #859
  Cargo.lock
  node/cli/Cargo.toml
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/service.rs
  pallets/schemas/src/tests.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch, Storage Migration

#1043 Event Custom RPC
  Cargo.lock
  common/primitives/Cargo.toml
  common/primitives/src/lib.rs
  common/primitives/src/rpc.rs
  integration-tests/package-lock.json
  js/api-augment/definitions/frequency.ts
  js/api-augment/definitions/index.ts
  js/api-augment/test/index.test.ts
  node/service/Cargo.toml
  node/service/src/rpc/frequency_rpc.rs
  node/service/src/rpc/mod.rs
  node/service/src/rpc/tests/mod.rs
  node/service/src/rpc/tests/rpc_mock.rs
  runtime/frequency/Cargo.toml
  runtime/frequency/src/lib.rs
  runtime/system-runtime-api/Cargo.toml
  runtime/system-runtime-api/src/lib.rs
Labels: metadata-mismatch

#1101 Add Multisig Pallet
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/frequency/Cargo.toml
  runtime/frequency/src/lib.rs
  scripts/run_all_benchmarks.sh
Labels: metadata-mismatch

#1089 578 - Initial implementation of council based schema creation
  Cargo.lock
  common/primitives/src/node.rs
  pallets/msa/src/audit_replay_tests.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/mock.rs
  pallets/msa/src/signature_registry_tests.rs
  pallets/schemas/Cargo.toml
  pallets/schemas/src/benchmarking.rs
  pallets/schemas/src/lib.rs
  pallets/schemas/src/mock.rs
  pallets/schemas/src/tests.rs
  pallets/schemas/src/weights.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1105 Zero-out staking account if unstake to below minimum
  common/primitives/src/capacity.rs
  pallets/capacity/src/benchmarking.rs
  pallets/capacity/src/extrinsics_tests.rs
  pallets/capacity/src/helpers_tests.rs
  pallets/capacity/src/lib.rs
  pallets/capacity/src/types.rs
  pallets/capacity/src/types_tests.rs
Labels: metadata-mismatch, Capacity

#1120 Deprecated revoke_schema_permissions()
  pallets/msa/src/lib.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1064 feat(Capacity) pay_with_capacity extrinsic
  Cargo.lock
  pallets/frequency-tx-payment/Cargo.toml
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/mock.rs
  pallets/frequency-tx-payment/src/tests.rs
  runtime/frequency/Cargo.toml
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1142 chore(staking): add integration test
  integration-tests/capacity/staking.test.ts
  integration-tests/scaffolding/extrinsicHelpers.ts
Labels: metadata-mismatch

#1138 feat(tx-payment): add ability to use Capacity
  Cargo.lock
  common/primitives/src/capacity.rs
  pallets/capacity/src/lib.rs
  pallets/frequency-tx-payment/Cargo.toml
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/mock.rs
  pallets/frequency-tx-payment/src/tests.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch

#1147 Initial implementation of revised retire_msa() design
  common/primitives/src/msa.rs
  pallets/msa/Cargo.toml
  pallets/msa/src/benchmarking.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/mock.rs
  pallets/msa/src/tests.rs
  pallets/msa/src/weights.rs
  runtime/frequency/src/lib.rs
Labels: metadata-mismatch
