Repository frequency-chain/frequency, pull requests merged in 2025-09, with the labels that each got.

#2585 feat: update frequency runtime call for bridging support in metadata generation
  js/api-augment/definitions/frequency.ts
  scripts/generate_js_definitions.sh
Labels: bug

#2587 Update provider registry and application registry via governance
  e2e/msa/update_provider_application.test.ts
  e2e/scaffolding/extrinsicHelpers.ts
  pallets/msa/README.md
  pallets/msa/src/benchmarking.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/migration/v2.rs
  pallets/msa/src/tests/application_tests.rs
  pallets/msa/src/tests/governance_tests.rs
  pallets/msa/src/tests/mock.rs
  pallets/msa/src/tests/mod.rs
  pallets/msa/src/tests/recovery_tests.rs
  pallets/msa/src/tests/update_tests.rs
  pallets/msa/src/weights.rs
  runtime/frequency/src/lib.rs
Labels: metadata-changed

#2589 Update crates and toolchain
  .github/workflows/benchmarks-run.yml
  .github/workflows/check-migrations.yml
  .github/workflows/merge-pr.yml
  .github/workflows/release.yml
  .github/workflows/verify-pr-commit.yml
  .tool-versions
  Cargo.lock
  README.md
  common/helpers/src/rpc.rs
  common/primitives/src/signatures.rs
  common/primitives/src/utils.rs
  deny.toml
  emulated-test/Cargo.lock
  node/cli/src/benchmarking.rs
  node/cli/src/command.rs
  node/cli/src/run_as_localchain.rs
  node/cli/src/run_as_parachain.rs
  node/service/src/block_sealing.rs
  node/service/src/chain_spec.rs
  node/service/src/common.rs
  node/service/src/service.rs
  node/src/main.rs
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/rpc/src/lib.rs
  pallets/handles/src/rpc/src/lib.rs
  pallets/messages/src/rpc/src/lib.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/offchain_storage.rs
  pallets/msa/src/rpc/src/lib.rs
  pallets/passkey/src/lib.rs
  pallets/schemas/src/lib.rs
  pallets/schemas/src/rpc/src/lib.rs
  pallets/stateful-storage/src/lib.rs
  pallets/stateful-storage/src/rpc/src/lib.rs
  pallets/treasury/src/lib.rs
  runtime/frequency/src/genesis/helpers.rs
  runtime/frequency/src/genesis/presets.rs
  runtime/frequency/src/lib.rs
  rust-toolchain.toml
Labels: metadata-changed

#2598 Lock NPM Packages
  e2e/package.json
  js/api-augment/package-lock.json
  js/api-augment/package.json
  js/ethereum-utils/package-lock.json
  js/ethereum-utils/package.json
  js/recovery-sdk/package-lock.json
  js/recovery-sdk/package.json
  js/schemas/package-lock.json
  js/schemas/package.json
  js/schemas/scripts/package.json
  scripts/js/onboard/package.json
  tools/eth-migration/package.json
  tools/genesis-data/package.json
  tools/state-copy/package.json
Labels: chore

#2603 2580 migrate schemas to schemas 20
  .github/workflows/verify-pr-commit.yml
  Cargo.lock
  Makefile
  common/helpers/Cargo.toml
  common/helpers/src/avro.rs
  common/helpers/src/avro_tests.rs
  common/helpers/src/lib.rs
  common/helpers/src/types.rs
  common/primitives/src/benchmarks.rs
  common/primitives/src/schema.rs
  js/api-augment/definitions/schemas.ts
  js/api-augment/test/index.test.ts
  node/service/Cargo.toml
  node/service/src/rpc/mod.rs
  pallets/messages/src/benchmarking.rs
  pallets/messages/src/rpc/src/lib.rs
  pallets/messages/src/rpc/src/tests/mod.rs
  pallets/messages/src/runtime-api/src/lib.rs
  pallets/messages/src/tests/mock.rs
  pallets/schemas/Cargo.toml
  pallets/schemas/README.md
  pallets/schemas/src/benchmarking.rs
  pallets/schemas/src/lib.rs
  pallets/schemas/src/migration/mod.rs
  pallets/schemas/src/migration/v4/mod.rs
  pallets/schemas/src/migration/v5.rs
  pallets/schemas/src/rpc/Cargo.toml
  pallets/schemas/src/rpc/src/lib.rs
  pallets/schemas/src/rpc/src/tests/mod.rs
  pallets/schemas/src/rpc/src/tests/rpc_mock.rs
  pallets/schemas/src/runtime-api/src/lib.rs
  pallets/schemas/src/tests/intent_tests.rs
  pallets/schemas/src/tests/mock.rs
  pallets/schemas/src/tests/other_tests.rs
  pallets/schemas/src/types.rs
  pallets/schemas/src/weights.rs
  pallets/stateful-storage/src/benchmarking.rs
  pallets/stateful-storage/src/lib.rs
  pallets/stateful-storage/src/tests/mock.rs
  resources/genesis-schemas.json
  runtime/frequency/src/genesis/helpers.rs
  runtime/frequency/src/lib.rs
  scripts/init.sh
  tools/genesis-data/getSchema.mjs
  tools/genesis-data/package-lock.json
  tools/genesis-data/package.json
  tools/genesis-data/schemas.mjs
Labels: metadata-changed, metadata-version-not-incremented

#2549 Provider Context: Minimal Profile for Provider and Applications
  .github/workflows/release.yml
  .github/workflows/verify-pr-commit.yml
  Cargo.lock
  Cargo.toml
  common/primitives/Cargo.toml
  common/primitives/src/cid.rs
  common/primitives/src/lib.rs
  common/primitives/src/msa.rs
  common/primitives/src/utils.rs
  designdocs/provider_contexts.md
  e2e/msa/frequency.png
  e2e/msa/provider_applications.test.ts
  e2e/msa/provider_governance.test.ts
  e2e/msa/recoverAccount.test.ts
  e2e/msa/update_provider_application.test.ts
  e2e/scaffolding/extrinsicHelpers.ts
  e2e/scaffolding/helpers.ts
  e2e/scenarios/grantDelegation.ethereum.test.ts
  pallets/capacity/src/tests/mock.rs
  pallets/capacity/src/tests/testing_utils.rs
  pallets/capacity/src/weights.rs
  pallets/frequency-tx-payment/src/benchmarking.rs
  pallets/frequency-tx-payment/src/capacity_stable_weights.rs
  pallets/frequency-tx-payment/src/tests/mock.rs
  pallets/messages/Cargo.toml
  pallets/msa/Cargo.toml
  pallets/msa/README.md
  pallets/msa/src/benchmarking.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/migration/mod.rs
  pallets/msa/src/migration/v1/mod.rs
  pallets/msa/src/migration/v2.rs
  pallets/msa/src/runtime-api/src/lib.rs
  pallets/msa/src/tests/application_tests.rs
  pallets/msa/src/tests/creation_tests.rs
  pallets/msa/src/tests/delegation_tests.rs
  pallets/msa/src/tests/governance_tests.rs
  pallets/msa/src/tests/migration_tests.rs
  pallets/msa/src/tests/mock.rs
  pallets/msa/src/tests/mod.rs
  pallets/msa/src/tests/other_tests.rs
  pallets/msa/src/tests/recovery_tests.rs
  pallets/msa/src/tests/replay_tests.rs
  pallets/msa/src/tests/retirement_tests.rs
  pallets/msa/src/tests/signed_extension_tests.rs
  pallets/msa/src/tests/update_tests.rs
  pallets/msa/src/types.rs
  pallets/msa/src/weights.rs
  runtime/common/src/constants.rs
  runtime/frequency/src/lib.rs
Labels: metadata-changed
