Repository frequency-chain/frequency, pull requests merged in 2025-05, with the labels that each got.

#2358 feat: custom runtime functions to generate deterministic Eth address from an MSA ID
  Cargo.lock
  Cargo.toml
  common/primitives/src/msa.rs
  deny.toml
  e2e/miscellaneous/balance.ethereum.test.ts
  e2e/msa/msaTokens.test.ts
  e2e/scaffolding/ethereum.ts
  pallets/msa/Cargo.toml
  pallets/msa/README.md
  pallets/msa/src/lib.rs
  pallets/msa/src/runtime-api/src/lib.rs
  pallets/msa/src/tests/other_tests.rs
  runtime/frequency/Cargo.toml
  runtime/frequency/src/lib.rs
Labels: metadata-changed

#2382 Add arm64 binaries and docker containers
  .github/workflows/benchmarks-run.yml
  .github/workflows/check-migrations.yml
  .github/workflows/check-polkadot-releases.yml
  .github/workflows/common/codecov/action.yml
  .github/workflows/common/srtool/action.yml
  .github/workflows/e2e-testnet.yml
  .github/workflows/merge-pr.yml
  .github/workflows/release.yml
  .github/workflows/verify-pr-commit.yml
  docker/collator-node-local.dockerfile
  docker/parachain-node-mainnet.overview.md
  docker/parachain-node-testnet.overview.md
  docker/parachain-node.dockerfile
  docker/standalone-node.dockerfile
  e2e/package-lock.json
  runtime/frequency/src/lib.rs
  scripts/init.sh
  scripts/run_collator.sh
Labels: metadata-changed

#2385 init: eip-712 support
  Cargo.lock
  common/primitives/Cargo.toml
  common/primitives/src/handles.rs
  common/primitives/src/node.rs
  common/primitives/src/signatures.rs
  common/primitives/src/utils.rs
  e2e/miscellaneous/balance.ethereum.test.ts
  e2e/msa/keyManagement.ethereum.test.ts
  e2e/msa/msaTokens.test.ts
  e2e/package-lock.json
  e2e/package.json
  e2e/passkey/passkeyProxy.ethereum.test.ts
  e2e/scaffolding/ethereum.ts
  e2e/scaffolding/helpers.ts
  pallets/handles/src/lib.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/tests/creation_tests.rs
  pallets/msa/src/tests/other_tests.rs
  pallets/msa/src/types.rs
  pallets/passkey/Cargo.toml
  pallets/passkey/src/lib.rs
  pallets/passkey/src/tests.rs
  pallets/passkey/src/types.rs
  pallets/stateful-storage/Cargo.toml
  pallets/stateful-storage/src/lib.rs
  pallets/stateful-storage/src/tests/other_tests.rs
  pallets/stateful-storage/src/types.rs
  runtime/common/src/signature.rs
  runtime/frequency/src/lib.rs
  tools/eth-migration/README.md
  tools/eth-migration/metamask.html
  tools/eth-migration/package-lock.json
Labels: metadata-changed

#2407 Feat/add xcm runtime apis
  .github/workflows/verify-pr-commit.yml
  Cargo.lock
  Cargo.toml
  Makefile
  deny.toml
  runtime/frequency/Cargo.toml
  runtime/frequency/src/lib.rs
  runtime/frequency/src/xcm/mod.rs
  runtime/frequency/src/xcm/tests/check_whitelist.rs
  runtime/frequency/src/xcm/tests/fee_estimation.rs
  runtime/frequency/src/xcm/tests/mock.rs
  runtime/frequency/src/xcm/tests/mod.rs
Labels: enhancement, metadata-changed

#2413 HotFix PR: Upgrade to latest stable2503
  .github/workflows/verify-pr-commit.yml
  Cargo.lock
  Cargo.toml
  deny.toml
  runtime/frequency/src/lib.rs
Labels: metadata-changed, metadata-version-not-incremented

#2403 Subsidize adding an Ethereum compatible control key
  common/primitives/src/msa.rs
  common/primitives/src/signatures.rs
  e2e/capacity/transactions.test.ts
  e2e/msa/addKeyLowCost.ethereum.test.ts
  e2e/msa/msaTokens.test.ts
  e2e/package-lock.json
  e2e/package.json
  e2e/scaffolding/extrinsicHelpers.ts
  pallets/frequency-tx-payment/src/lib.rs
  pallets/frequency-tx-payment/src/tests/mock.rs
  pallets/frequency-tx-payment/src/tests/pallet_tests.rs
  pallets/frequency-tx-payment/src/types.rs
  pallets/msa/src/benchmarking.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/tests/delegation_tests.rs
  pallets/msa/src/tests/mod.rs
  pallets/msa/src/tests/subsidized_add_key_tests.rs
  runtime/frequency/src/lib.rs
Labels: metadata-changed

#2418 [AGENT] add safe xcm version migration
  Makefile
  runtime/common/src/constants.rs
  runtime/frequency/src/lib.rs
  runtime/frequency/src/migration_tests.rs
  runtime/frequency/src/xcm/tests/mock.rs
  runtime/frequency/src/xcm/tests/mod.rs
  scripts/init.sh
Labels: codex
