Repository frequency-chain/frequency, pull requests merged in 2025-07, with the labels that each got.

#2496 Implement recover_account
  Makefile
  designdocs/recovery_system.md
  e2e/capacity/transactions.test.ts
  e2e/msa/recoverAccount.test.ts
  e2e/scaffolding/extrinsicHelpers.ts
  e2e/scaffolding/helpers.ts
  pallets/frequency-tx-payment/src/capacity_stable_weights.rs
  pallets/frequency-tx-payment/src/tests/stable_weights_tests.rs
  pallets/msa/README.md
  pallets/msa/src/benchmarking.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/tests/mock.rs
  pallets/msa/src/tests/recovery_tests.rs
  pallets/msa/src/types.rs
  pallets/msa/src/weights.rs
  runtime/frequency/src/lib.rs
Labels: enhancement, metadata-changed

#2511 feat: Add autogenerated weights for pallet_xcm
  Cargo.lock
  Makefile
  runtime/common/Cargo.toml
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/pallet_assets.rs
  runtime/common/src/weights/pallet_message_queue.rs
  runtime/frequency/Cargo.toml
  runtime/frequency/src/genesis/westend.rs
  runtime/frequency/src/lib.rs
  scripts/run_benchmarks.sh
Labels: benchmark

#2520 upgrade to polkadot-stable2503-7
  Cargo.lock
  Cargo.toml
  docker/docker-compose.yml
  e2e/package-lock.json
  js/api-augment/package-lock.json
  js/ethereum-utils/package-lock.json
  js/schemas/package-lock.json
  runtime/frequency/src/lib.rs
Labels: metadata-changed

#2461 2456 bug can unstake and then immediately restake entire amount
  e2e/capacity/staking.test.ts
  pallets/capacity/src/lib.rs
  pallets/capacity/src/tests/stake_and_deposit_tests.rs
  pallets/capacity/src/tests/testing_utils.rs
  pallets/capacity/src/weights.rs
  runtime/frequency/src/lib.rs
  scripts/generate_js_definitions.sh
Labels: metadata-changed

#2311 Design Doc: Provider Contexts
  designdocs/README.md
  designdocs/provider_contexts.md
Labels: discussion
