Repository frequency-chain/frequency, pull requests merged in 2025-08, with the labels that each got.

#2535 feat: add model validation support for optional fields in Parquet schemas
  common/primitives/src/parquet/column.rs
  e2e/scaffolding/extrinsicHelpers.ts
  e2e/schemas/createSchema.test.ts
  e2e/schemas/fixtures/index.ts
  pallets/schemas/src/tests/other_tests.rs
  pallets/schemas/src/weights.rs
  runtime/frequency/src/lib.rs
Labels: metadata-changed

#2537 [Provider Context] Update provider creation to intake new payload + changes around it
  Cargo.lock
  Cargo.toml
  Makefile
  common/primitives/src/msa.rs
  e2e/miscellaneous/utilityBatch.test.ts
  e2e/msa/provider_v1.test.ts
  e2e/msa/provider_v2.test.ts
  e2e/msa/recoverAccount.test.ts
  e2e/scaffolding/extrinsicHelpers.ts
  e2e/scaffolding/helpers.ts
  e2e/scenarios/grantDelegation.ethereum.test.ts
  pallets/capacity/src/tests/mock.rs
  pallets/capacity/src/tests/testing_utils.rs
  pallets/frequency-tx-payment/src/benchmarking.rs
  pallets/frequency-tx-payment/src/tests/mock.rs
  pallets/messages/Cargo.toml
  pallets/msa/Cargo.toml
  pallets/msa/src/benchmarking.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/migration/mod.rs
  pallets/msa/src/migration/v1/mod.rs
  pallets/msa/src/migration/v2.rs
  pallets/msa/src/tests/creation_tests.rs
  pallets/msa/src/tests/delegation_tests.rs
  pallets/msa/src/tests/governance_tests.rs
  pallets/msa/src/tests/mock.rs
  pallets/msa/src/tests/other_tests.rs
  pallets/msa/src/tests/recovery_tests.rs
  pallets/msa/src/tests/replay_tests.rs
  pallets/msa/src/tests/retirement_tests.rs
  pallets/msa/src/tests/signed_extension_tests.rs
  pallets/msa/src/types.rs
  pallets/msa/src/weights.rs
  runtime/common/src/constants.rs
  runtime/frequency/src/lib.rs
Labels: metadata-changed, change/storage-migration

#2312 Design Doc: Schemas, Intents, and Delegation Groups
  designdocs/README.md
  designdocs/schemas_protocols_intents.md
  e2e/msa/msaKeyManagement.test.ts
Labels: discussion

#2546 Test/xcm version subscription
  designdocs/xcm_version_subscription.md
  emulated-test/Cargo.lock
  emulated-test/test/frequency-westend/src/lib.rs
  emulated-test/test/frequency-westend/src/tests/execute_transact_instruction_fails.rs
  emulated-test/test/frequency-westend/src/tests/mod.rs
  emulated-test/test/frequency-westend/src/tests/reserve_transfer_dot_to_assethub.rs
  emulated-test/test/frequency-westend/src/tests/reserve_transfer_dot_to_relay.rs
  emulated-test/test/frequency-westend/src/tests/reserve_transfer_xfrqcy_with_dot_fee_from_assethub_fails.rs
  emulated-test/test/frequency-westend/src/tests/send_xcm_to_relay_with_root.rs
  emulated-test/test/frequency-westend/src/tests/teleport_xfqcy_from_asset_hub_without_checking_fails.rs
  emulated-test/test/frequency-westend/src/tests/teleport_xfrqcy_to_assethub_with_dot_fee.rs
  emulated-test/test/frequency-westend/src/tests/teleport_xfrqcy_with_dot_fee_from_assethub.rs
  emulated-test/test/frequency-westend/src/tests/utils.rs
  emulated-test/test/frequency-westend/src/tests/xcm_version_subscription.rs
  runtime/frequency/src/xcm/barrier.rs
  runtime/frequency/src/xcm/queue.rs
Labels: metadata-changed, test

#2565 Provider Context Upload Logo Extrinsic
  Cargo.lock
  Cargo.toml
  common/primitives/Cargo.toml
  common/primitives/src/cid.rs
  common/primitives/src/lib.rs
  e2e/msa/frequency.png
  e2e/msa/provider_applications.test.ts
  e2e/scaffolding/extrinsicHelpers.ts
  e2e/scaffolding/helpers.ts
  pallets/messages/Cargo.toml
  pallets/msa/src/benchmarking.rs
  pallets/msa/src/lib.rs
  pallets/msa/src/tests/application_tests.rs
  pallets/msa/src/types.rs
  pallets/msa/src/weights.rs
Labels: metadata-changed
